import {
  Box,
  VStack,
} from '@chakra-ui/react'
import React, { memo } from 'react'
import Header from '@components/Header/Header'
import Footer from '@components/Footer/Footer'
import Head from 'next/head'
export const Layout = ({ children }: { children: any }) => {
  return (
    <VStack w={'100%'} h={'100%'} flexDirection={"column"} bg={"white"} color={"black"}>
      <Head>
        <title>724Desk</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        w={'full'}
        h={'full'}
        pos={'sticky'}
        top={0}
        // backdropFilter='blur(90px)' filter = 'grayscale(10%)'
        // backdropContrast='100%'
        zIndex={4}
      >
        <Header />
      </Box>
      <Box w={'full'} h={'full'}>
        {children}
      </Box>
      <Box w={'full'} h={'full'}>
        <Footer />
      </Box>
    </VStack>
  )
}

export default memo(Layout)
